---
- name: Instalar e configurar Zabbix Agent 2
  hosts: all
  become: yes

  vars:
    zabbix_server_ip: "192.168.100.0/24"
    zabbix_agent_conf_path: "/etc/zabbix/zabbix_agent2.conf"

  tasks:

    - name: Adicionar repositório do Zabbix (Debian/Ubuntu)
      apt:
        deb: "http://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+{{ ansible_distribution|lower }}{{ ansible_distribution_version|regex_replace('\\.', '') }}_all.deb"
        
        state: present
       
      when: ansible_os_family == "Debian"

    - name: Atualizar cache do apt
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Instalar Zabbix Agent2 (Debian/Ubuntu)
      apt:
        name: zabbix-agent2
        state: present
      when: ansible_os_family == "Debian"

    - name: Adicionar repositório do Zabbix (CentOS/RHEL/OracleLinux)
      yum:
        name: "http://repo.zabbix.com/zabbix/6.4/rhel/{{distribution_major_version|lower}}/x86_64/zabbix-release-6.4-1.el{{distribution_major_version|lower}}.noarch.rpm"
        state: present
      when: ansible_os_family == "RedHat"

    - name: Atualizar cache do yum
      yum:
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Instalar Zabbix Agent2 (CentOS/RHEL/OracleLinux)
      yum:
        name: zabbix-agent2
        state: present
      when: ansible_os_family == "RedHat"

    - name: Configurar arquivo zabbix_agent2.conf com server IP
      lineinfile:
        path: "{{ zabbix_agent_conf_path }}"
        regexp: "^Server="
        line: "Server={{ zabbix_server_ip }}"
        state: present
        backup: yes

    - name: Configurar arquivo zabbix_agent2.conf com server active IP
      lineinfile:
        path: "{{ zabbix_agent_conf_path }}"
        regexp: "^ServerActive="
        line: "ServerActive={{ zabbix_server_ip }}"
        state: present
        backup: yes

    - name: Habilitar e iniciar o serviço zabbix-agent2
      systemd:
        name: zabbix-agent2
        enabled: yes
        state: restarted
